# fly.toml file generated for delivery-app on 2023-08-02T17:08:04-05:00

app = "delivery-app"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
